name: Deployment pipeline
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Trae el repositorio
        with:
          fetch-depth: 0 # Solo trae el último commit para rapidez

      - uses: actions/setup-node@v2 # Configura Node.js
        with:
          node-version: '12' # Versión de Node a usar [13]

      - name: Install dependencies
        run: npm install --no-audit --no-fund # Instala dependencias optimizado

      - name: Linter
        run: npm run lint # Ejecuta el linter

      - name: Build
        run: npm run build # Ejecuta la build

      - name: Test
        run: npm run test # Ejecuta los tests unitarios